title: "Hdert's website"
description: "A website with Hdert's projects and contact information"
url: https://www.hdert.com

theme: cvless

# site settings
cv: false

# lsi: false
# safe: true
# source: ./
# incremental: false
# highlighter: rouge
# gist:
#     noscript: false
# kramdown:
#     math_engine: mathjax
#     syntax_highlighter: rouge
# repository: hdert/hdert.github.io

# author settings
author:
    name: Hdert
    email: contact@hdert.com

# profile links
profile:
    mastodon: https://mastodon.social/@hdert
    linkedin: https://www.linkedin.com/in/justinmuirhead
    github: https://github.com/hdert
    cv: false

# build settings
permalink: pretty
exclude:
    - LICENSE
    - README.md
    - Gemfile
    - vendor

plugins:
    - jekyll-feed
    - jekyll-gist
    - jekyll-paginate-v2
    - jekyll-seo-tag
    - jekyll-sitemap

sass:
    sourcemap: never
